samples/SampleApp/App.axaml, samples/SampleApp/MainWindow.axaml, samples/SampleApp/SampleApp.csproj, src/Devolutions.MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/Button.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/TabControl.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/TabItem.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/TextBlock.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/ToggleSwitch.axaml
**Update Sampler**
- just updating to the changed theme name/folder
**Resource structure & naming scheme** 
- This might still need to evolve as more controls come into the the theme, but hopefully it's a decent start with a consistent approach & not too complicated
(no meaningful changes to `ToggleSwitch`, just the linter finally caught up to its 4-space indentation)
=> Refactor resource structure & update Sampler for new theme name

src/Devolutions.MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/Devolutions.MacOS.Avalonia.Theme/Controls/ComboBox.axaml, src/Devolutions.MacOS.Avalonia.Theme/Converters/SelectedIndexToPopupOffsetConverter.cs
Button height had been affected by some later changes to control border thickness ...
=> Fix button height & add padding to ComboBox popup

samples/SampleApp/DemoPages/Overview.axaml
=> Remove an experiment from the Sample app 

src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
This is just as a first stab for development, so that controls don't completely disappear in dark mode
=> First stab at dark-mode

samples/SampleApp/Assets/Padlock.svg, src/MacOS.Avalonia.Theme/Controls/CheckBox.axaml, src/MacOS.Avalonia.Theme/Controls/ComboBoxItem.axaml, src/MacOS.Avalonia.Theme/Controls/TabControl.axaml, src/MacOS.Avalonia.Theme/Controls/TabItem.axaml, src/MacOS.Avalonia.Theme/MacOS.Avalonia.Theme.csproj
Just fixing some naming issues and removing redundant code
=> Tidy up some code

.gitignore, samples/SampleApp/DemoPages/ContextMenuDemo.axaml, samples/SampleApp/DemoPages/ContextMenuDemo.axaml.cs, samples/SampleApp/DemoPages/MenuDemo.axaml, samples/SampleApp/DemoPages/MenuDemo.axaml.cs, samples/SampleApp/DemoPages/MenuFlyoutDemo.axaml, samples/SampleApp/DemoPages/MenuFlyoutDemo.axaml.cs, samples/SampleApp/MainWindow.axaml, src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/MacOS.Avalonia.Theme/Controls/ComboBox.axaml, src/MacOS.Avalonia.Theme/Controls/Menu.axaml, src/MacOS.Avalonia.Theme/Controls/MenuFlyoutPresenter.axaml, src/MacOS.Avalonia.Theme/Controls/MenuItem.axaml, src/MacOS.Avalonia.Theme/Controls/Separator.axaml, src/MacOS.Avalonia.Theme/Controls/_index.axaml
=> Add MenuFlyout (context menu) & MenuItem styling

samples/SampleApp/DemoPages/ContextMenuDemo.axaml, samples/SampleApp/DemoPages/MenuDemo.axaml, samples/SampleApp/MainWindow.axaml, src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/MacOS.Avalonia.Theme/Controls/ContextMenu.axaml, src/MacOS.Avalonia.Theme/Controls/Menu.axaml, src/MacOS.Avalonia.Theme/Controls/MenuFlyoutPresenter.axaml, src/MacOS.Avalonia.Theme/Controls/MenuItem.axaml, src/MacOS.Avalonia.Theme/Controls/_index.axaml
=> Add Menu & ContextMenu

samples/SampleApp/DemoPages/GridSplitterDemo.axaml, samples/SampleApp/DemoPages/GridSplitterDemo.axaml.cs, samples/SampleApp/MainWindow.axaml, src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/MacOS.Avalonia.Theme/Controls/GridSplitter.axaml, src/MacOS.Avalonia.Theme/Controls/_index.axaml
=> Add GridSplitter styling

samples/SampleApp/DemoPages/MenuDemo.axaml, src/MacOS.Avalonia.Theme/Accents/Assets/TestIconForDesignPreview.svg, src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/MacOS.Avalonia.Theme/Controls/Menu.axaml, src/MacOS.Avalonia.Theme/Controls/MenuItem.axaml
- adding vertical separator 
- fixing vertical alignment
- fixing the display of empty space to the right of Sub-MenuItems when no shortcut key is given
- fixing custom sizing/spacing options and adding usage examples to the MenuDemo code
=> Various Menu fixes

src/MacOS.Avalonia.Theme/Controls/DataGrid.axaml
=> Add rounded selection highlights to DataGrid

samples/SampleApp/MainWindow.axaml, src/MacOS.Avalonia.Theme/Controls/Menu.axaml
=> Fix selected MenuItem highlight size

samples/SampleApp/DemoPages/ToolTipDemo.axaml, samples/SampleApp/DemoPages/ToolTipDemo.axaml.cs, samples/SampleApp/MainWindow.axaml, src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml, src/MacOS.Avalonia.Theme/Controls/ToolTip.axaml, src/MacOS.Avalonia.Theme/Controls/_index.axaml
=> Add Tooltip styling

samples/SampleApp/SampleApp.csproj, src/MacOS.Avalonia.Theme/MacOS.Avalonia.Theme.csproj
(updating manually despite the new Dependabot setup, since it's easiest to run a quick sanity test on all updated packages at once)
=> Update Avalonia packages to v11.2.5

src/DevExpress.Avalonia.Theme/Accents/ThemeResources.axaml, src/DevExpress.Avalonia.Theme/Controls/TabControl.axaml, src/DevExpress.Avalonia.Theme/Controls/TabItem.axaml
=> Adjust DevExpress tabs

samples/SampleApp/DemoPages/TextBoxDemo.axaml, src/DevExpress.Avalonia.Theme/Accents/Styles.axaml, src/DevExpress.Avalonia.Theme/Accents/ThemeResources.axaml, src/DevExpress.Avalonia.Theme/Controls/TabItem.axaml, src/DevExpress.Avalonia.Theme/Controls/TextBox.axaml, src/DevExpress.Avalonia.Theme/Controls/Window.axaml, src/DevExpress.Avalonia.Theme/Controls/_index.axaml, src/DevExpress.Avalonia.Theme/Converters/CharToDevExpressPasswordCharConverter.cs, src/DevExpress.Avalonia.Theme/Converters/RevealPasswordToFontSizeConverter.cs, src/DevExpress.Avalonia.Theme/Converters/_index.axaml, src/DevExpress.Avalonia.Theme/DevExpressTheme.axaml
=> [DevExpress] Add explicit default font & Textbox styling

src/DevExpress.Avalonia.Theme/Accents/Styles.axaml, src/DevExpress.Avalonia.Theme/Accents/ThemeResources.axaml, src/DevExpress.Avalonia.Theme/Controls/ComboBox.axaml, src/DevExpress.Avalonia.Theme/Controls/ComboBoxItem.axaml, src/DevExpress.Avalonia.Theme/Controls/TabControl.axaml, src/DevExpress.Avalonia.Theme/Controls/TextBox.axaml, src/DevExpress.Avalonia.Theme/Controls/Window.axaml, src/DevExpress.Avalonia.Theme/Controls/_index.axaml, src/DevExpress.Avalonia.Theme/Converters/BooleanToChoiceConverter.cs, src/DevExpress.Avalonia.Theme/Converters/_index.axaml, src/MacOS.Avalonia.Theme/Controls/ComboBoxItem.axaml
=> [DevExpress] Add ComboBox styling

samples/SampleApp/DemoPages/NumericUpDownDemo.axaml, samples/SampleApp/DemoPages/NumericUpDownDemo.axaml.cs, samples/SampleApp/MainWindow.axaml, src/DevExpress.Avalonia.Theme/Controls/TextBox.axaml, src/MacOS.Avalonia.Theme/Controls/ButtonSpinner.axaml, src/MacOS.Avalonia.Theme/Controls/NumericUpDown.axaml, src/MacOS.Avalonia.Theme/Controls/TextBox.axaml, src/MacOS.Avalonia.Theme/Controls/_index.axaml
=> [MacOS] Add NumericUpDown & ButtonSpinner styling

samples/SampleApp/DemoPages/ButtonDemo.axaml, src/DevExpress.Avalonia.Theme/Accents/ThemeResources.axaml, src/DevExpress.Avalonia.Theme/Controls/Button.axaml, src/DevExpress.Avalonia.Theme/Controls/ComboBox.axaml, src/DevExpress.Avalonia.Theme/Controls/ComboBoxItem.axaml, src/DevExpress.Avalonia.Theme/Controls/TabControl.axaml, src/DevExpress.Avalonia.Theme/Controls/TabItem.axaml, src/DevExpress.Avalonia.Theme/Controls/TextBox.axaml, src/DevExpress.Avalonia.Theme/Controls/_index.axaml
=> [DevExpress] Add Button styling

src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml
=> [MacOS] Remove soft shadow from TextBox

samples/SampleApp/App.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/Styles.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBoxItem.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/EmbeddableControlRoot.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/Window.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml
This replicates the default text styling approach from #105 for the DevExpress theme
=> [DevExpress] Add default text styling

src/Devolutions.AvaloniaTheme.DevExpress/Accents/Icons.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/Styles.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/CheckBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml, src/Devolutions.AvaloniaTheme.DevExpress/DevExpressTheme.axaml
=> [DevExpress] Add CheckBox styling 

src/Devolutions.AvaloniaTheme.DevExpress/Accents/Styles.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ContextMenu.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/EmbeddableControlRoot.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/Window.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml, src/Devolutions.AvaloniaTheme.DevExpress/DevExpressTheme.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj, src/Devolutions.AvaloniaTheme.DevExpress/README.md
- Themed the ContextMenu
- background color of embedded controls / windows
- Button font weight too light
- TextBox colors
- Slight DataGrid adjustments (temporary, we're still missing a proper DataGrid theme)
=> [DEVEX-168] Themed the ContextMenu plus some additional theming fixes

samples/SampleApp/App.axaml, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/Icons.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ScrollBar.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ScrollViewer.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml
=> [DevExpress] Add ScrollBar / ScrollViewer styling

samples/SampleApp/DemoPages/NumericUpDownDemo.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ButtonSpinner.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBoxItem.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/NumericUpDown.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Converters/BooleanAndThemeToChoiceConverter.cs, src/Devolutions.AvaloniaTheme.DevExpress/Converters/_index.axaml
=> [DevExpress] Add NumericUpDown styling & fix Combo hover state & dark mode colour

samples/SampleApp/App.axaml, samples/SampleApp/DemoPages/ControlAlignment.axaml, samples/SampleApp/DemoPages/ControlAlignment.axaml.cs, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/ButtonSpinner.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/CheckBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/ComboBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/ContextMenu.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/GridSplitter.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/Menu.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/MenuItem.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/NumericUpDown.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TabControl.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TabItem.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TreeViewItem.axaml
- fix alignment issues between controls of different type
- fix NumericUpDown focus outline being cut off
- fix/add tabbing focus to all controls
=> [MacOS] Fix various issues & add proper tabbing focus to all controls

samples/SampleApp/DemoPages/DataGridDemo.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/DataGrid.axaml
=> Fix DataGrid row rounded edge being cut off by ScrollBar

samples/SampleApp/DemoPages/AutoCompleteBoxDemo.axaml, samples/SampleApp/DemoPages/AutoCompleteBoxDemo.axaml.cs, samples/SampleApp/DemoPages/ControlAlignment.axaml, samples/SampleApp/DemoPages/ControlAlignment.axaml.cs, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj, src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj, src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/AutoCompleteBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/ListBoxItem.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/_index.axaml, src/Devolutions.AvaloniaTheme.MacOS/Devolutions.AvaloniaTheme.MacOS.csproj, src/Devolutions.AvaloniaTheme.MacOS/README.md
=> [MacOS] Add AutoCompleteBox

src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj, src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj, src/Devolutions.AvaloniaTheme.MacOS/Devolutions.AvaloniaTheme.MacOS.csproj
Duh! correcting wrong path in #198
=> Include readme in build correction

samples/SampleApp/DemoPages/ButtonDemo.axaml, src/Devolutions.AvaloniaTheme.Linux/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/EmbeddableControlRoot.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/Window.axaml
=> [Linux] Button styling

samples/SampleApp/DemoPages/DataGridDemo.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/DataGrid.axaml
Fix the square where horizontal & vertical scrollbar meet - which was transparent before
=> [DevExpress] Fix DataGrid scrollbar junction

samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaControls/Converters/DevoMultiConverters.cs, src/Devolutions.AvaloniaControls/Converters/FirstNonEmptyStringMultiConverter.cs, src/Devolutions.AvaloniaTheme.DevExpress/CHANGELOG.md, src/Devolutions.AvaloniaTheme.Linux/Accents/Icons.axaml, src/Devolutions.AvaloniaTheme.Linux/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.Linux/CHANGELOG.md, src/Devolutions.AvaloniaTheme.Linux/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/Calendar.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/CalendarButton.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/CalendarDatePicker.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/CalendarDayButton.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/CalendarItem.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/ContextMenu.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/EmbeddableControlRoot.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/TextBox.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/Window.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/_index.axaml
This mainly adds the styling for `CalendarDatePicker`, but in the course of that I also had to make some changes to `Button` and `TextBox` and started working on adding the fadiing behaviours when the Window becomes inactive.
<br />
<br />
=> [Linux] Add CalendarDatePicker & some additions to Button & TextBox

samples/SampleApp/DemoPages/TabControlDemo.axaml, samples/SampleApp/Styles.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/TabControl.axaml
=> [DevExpress] Make TabControl transparent for flexible use

src/Devolutions.AvaloniaTheme.Linux/Controls/Button.axaml, src/Devolutions.AvaloniaTheme.Linux/Controls/CalendarButton.axaml
Inadvertently left uncommented in #219
=> [Linux] Comment out local ResourceIncludes

samples/SampleApp/DemoPages/ControlAlignment.axaml, samples/SampleApp/DemoPages/RadioButtonDemo.axaml, samples/SampleApp/DemoPages/RadioButtonDemo.axaml.cs, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/RadioButton.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/_index.axaml
=> [MacOS] Add RadioButton styling

src/Devolutions.AvaloniaTheme.DevExpress/Controls/MultiComboBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/MultiComboBox.axaml
Additionally fix the templating of the selected items on MacOS like it was fixed for DevExpress.
=> MultiComboBox styling fixes to the DevExpress theme

src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/CheckBox.axaml, src/Devolutions.AvaloniaTheme.DevExpress/README.md
=> [DevExpress] Fix CheckBox :disabled:checked and focus:pointerover styles

samples/SampleApp/DemoPages/RadioButtonDemo.axaml, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/RadioButton.axaml, src/Devolutions.AvaloniaTheme.DevExpress/Controls/_index.axaml, src/Devolutions.AvaloniaTheme.DevExpress/README.md
=> [DevExpress] Add RadioButton styling

samples/SampleApp/DemoPages/ControlAlignment.axaml, samples/SampleApp/MainWindow.axaml, src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/ComboBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/Controls/EditableComboBox.axaml, src/Devolutions.AvaloniaTheme.MacOS/README.md
=> [MacOs] EditableComboBox styling
