- samples/SampleApp/DemoPages/ButtonDemo.axaml
- samples/SampleApp/DemoPages/CheckBoxDemo.axaml
- samples/SampleApp/DemoPages/CheckBoxDemo.axaml.cs
- samples/SampleApp/MainWindow.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Controls/Button.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Controls/CheckBox.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Controls/TabControl.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Controls/_index.axaml
This brings them more in line with the MacOS look.
> Add CheckBox styling & cleaner Button borders

- src/Devolutions.MacOS.Avalonia.Theme/Converters/SelectedIndexToPopupOffsetConverter.cs
- src/Devolutions.MacOS.Avalonia.Theme/Converters/TotalWidthConverter.cs
Just tidying up the code for the two converters used in `ComboBox.axaml`
> Refactor converters with early returns

- README.md
For some reason the animated gif palette completely ignores the light gray tones.
(Also trying one of the videos with the size set to 50% ... not working in the preview, but just in case that's just the preview engine(?)
> Replace gif's on README with mp4

- src/Devolutions.MacOS.Avalonia.Theme/Devolutions.MacOS.Avalonia.Theme.csproj
This should add a source link to the [package listing in the Nuget Gallery](https://www.nuget.org/packages/Devolutions.MacOS.Avalonia.Theme), so people can find the ReadMe with more info.
> Add source repo to package info (for nuget.org)

- src/Devolutions.MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
- src/Devolutions.MacOS.Avalonia.Theme/Controls/TextBox.axaml
The disabled background colour (white @ opacity 70%) didn't come through, because the box used to create the system-colour border, was set to be white when not in focus.
I also set the opacity to 50% now (despite [Apple Design Resources](https://www.figma.com/design/E0jwRwSdmCNREfsFJxRKyy/Apple-Design-Resources---macOS-(Community)?node-id=121-12220&t=OT2AzIQTqrAGJkPm-0) specifying 70%. On a light background it just seems to be very difficult to distinguish from an enabled TextBox with just a placeholder.
Some tweaks to the focus border. (I tried to get away from using a background to achieve the border, but couldn't get rid of a 1px gray line on the inside when using BorderBrush)
> Fix disabled TextBox & polish focus border

- src/Devolutions.MacOS.Avalonia.Theme/Controls/TextBox.axaml
Fixed the issue where TextBoxes with a given prefix or suffix to the user input displayed a little bit higher than plain ones.
> Fix prefix/suffix affecting TextBox height

- src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
This fixes bug I introduced when adding dark mode support (#30), leading to a run-time error when accessing a TextBox with Clear button, because its bg colour was not available.
> Fix TextBox Clear button

- src/MacOS.Avalonia.Theme/Controls/CheckBox.axaml
Setting custom `VerticalAlignment` & `VerticalContentAlignment` on a CheckBox resulted in internal misalignment. 
Now it works as expected:
> Fix CheckBox alignment

- README.md
- samples/SampleApp/DemoPages/MenuDemo.axaml
- samples/SampleApp/DemoPages/TreeViewDemo.axaml
- src/MacOS.Avalonia.Theme/Accents/Styles.axaml
- src/MacOS.Avalonia.Theme/Controls/Menu.axaml
- src/MacOS.Avalonia.Theme/Controls/TreeView.axaml
Just renaming the custom classes to make it clear that they belong to the MacOS theme and have no effect otherwise.
> Add Theme prefix to custom classes

- samples/SampleApp/DemoPages/DataGridDemo.axaml
- samples/SampleApp/DemoPages/MenuDemo.axaml
- samples/SampleApp/DemoPages/TreeViewDemo.axaml
- samples/SampleApp/MainWindow.axaml
- samples/SampleApp/SampleApp.csproj
- src/MacOS.Avalonia.Theme/Accents/Styles.axaml
- src/MacOS.Avalonia.Theme/Controls/Menu.axaml
- Fixing some icons that broke when I started using `<Svg>` to place icons.
- Removing unintuitive use of property `(Svg.Css)` - just `Css` seems to be working fine now ... 🙃
- Removing redundant SVG packages
> Tidy up after move to `<Svg>` instead of `<Image>`

- samples/SampleApp/DemoPages/GridSplitterDemo.axaml
- src/MacOS.Avalonia.Theme/Controls/GridSplitter.axaml
Fix the `GridSplitter` to show the thin divider line correctly when used as horizontal divider
> Make GridSplitter work in horizontal direction too

- src/MacOS.Avalonia.Theme/Controls/ScrollViewer.axaml
The multiline `TextBox` didn't seem to respond to scrolling very reliably. 
Turns out `ScrollContentPresenter` requires a default background colour (just `Transparent` is fine), otherwise it cannot receive pointer events, and scrolling will not work while the pointer is over areas of whitespace between the text.
> Fix intermittent unresponsiveness of TextBox scrolling

- src/MacOS.Avalonia.Theme/Accents/Styles.axaml
- src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
- src/MacOS.Avalonia.Theme/Controls/Button.axaml
- src/MacOS.Avalonia.Theme/Controls/CheckBox.axaml
- src/MacOS.Avalonia.Theme/Controls/ComboBox.axaml
- src/MacOS.Avalonia.Theme/Controls/DataGrid.axaml
- src/MacOS.Avalonia.Theme/Controls/TreeViewItem.axaml
- src/MacOS.Avalonia.Theme/Controls/Window.axaml
- src/MacOS.Avalonia.Theme/Controls/_index.axaml
In RDM, currently the main consumer of this MacOS theme, Avalonia views are embedded into a native app, by-passing the typical structure of an Avalonia app where all controls have a _Window_ as their ancestor. 
This PR removes the reliance on the presence of a Window at the root by:
- Setting an explicit font not only on `Window` (overriding Fluent's font settings) _but also_ on `TextBlock`, since in RDM's setup inheritance from the Window doesn't work
- Changing all styling conditional on the Window state, to default to the assumption that the window is active, if no Window is found. This breaks the mechanism for indicating wether the window is active or not for RDM, but keeps it intact for normal apps using the theme. 
Perhaps we can find a way to pass the native window state into a …
> Remove styling-dependance on the presence of a window at the root

- src/MacOS.Avalonia.Theme/Controls/DataGrid.axaml
- src/MacOS.Avalonia.Theme/Converters/IsExplicitlyTrueConverter.cs
- src/MacOS.Avalonia.Theme/Converters/IsUnsetConverter.cs
- src/MacOS.Avalonia.Theme/Converters/_index.axaml
The boolean logic governing the foreground colour of a DataGrid row (based on whether it's selected or not, and whether the parent window is active or not) broke for RDM where views embedded directly into the native app do not have a window ancestor. 
This solution seems rather convoluted, but it works around the fact that Avalonia AND/OR converters do return a boolean when any of the input unset (even if that input wouldn't need to be evaluated based on the other input).
> Fix white on white text in DataGrid

- src/DevExpress.Avalonia.Theme/Controls/TabItem.axaml
Had some second thoughts on making tab height independent of fonts - hopefully with `MinHeight` there is wriggle room for different fonts' line heights not affecting the tab height, but tabs can still grow to accommodate non-standard content (like larger icons)
> [DevExpress] Change fixed tab height to MinHeight

- src/DevExpress.Avalonia.Theme/Accents/ThemeResources.axaml
- src/DevExpress.Avalonia.Theme/Controls/TabControl.axaml
- src/DevExpress.Avalonia.Theme/Controls/TabItem.axaml
- src/DevExpress.Avalonia.Theme/Converters/TabBorderVisibilityConverter.cs
- Adjusting size to match actual DevExpress 
- Change the accent line to only show up when tab is focussed
- Some changes to avoid overlapping lines (on my Mac screen the overlapping line sections are perfectly aligned (as they should be in theory), but on Windows or certain screens they appear just offset enough to be noticeable when you look very closely)
> [DevExpress] Tweak TabControl 

- samples/SampleApp/App.axaml
- samples/SampleApp/DemoPages/TextBoxDemo.axaml
- src/MacOS.Avalonia.Theme/Accents/ThemeResources.axaml
- src/MacOS.Avalonia.Theme/Controls/TextBox.axaml
- Updates the fontsize for the hidden-password character, which after the font change in #63 looked too small:
- Fixed the issue where setting the height of a TextBox always resulted in an apparent height 6 pixels less, because the focus highlight was taken into account.
- Changing the way the focus border is created also fixed the tiny layout jumps when focussing a TextBox
> [MacOS Theme] Fix various Textbox issues

- samples/SampleApp/DemoPages/TextBoxDemo.axaml
- src/MacOS.Avalonia.Theme/Controls/TextBox.axaml
#85 affected the TextBox padding and an earlier mistake within the local Demo styling lead to misleading results in the app. 
Both should be fixed with this
> Adjust MacOS TextBox Padding

- .github/workflows/build-package.yml
The build-package workflow from #89 quietly fails in the publish step - I assume it's just this small typo.
> Fix typo in build-package workflow

- src/Devolutions.AvaloniaTheme.DevExpress/Accents/Styles.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/Styles.axaml
This fixes spacing issues in RDM, where the embedded views do not have a parent Window and therefore don't inherit the default font. This applies the work-around used for `TextBlock` to `AccessText` also.
> Propagate default font to AccessText without parent Window

- src/Devolutions.AvaloniaTheme.MacOS/Controls/ComboBox.axaml
The ComboBox button exhibits strange variation in how it's rendered - here two screenshots, Retina display & external monitor:
Since the NumericUpDown control (using the same chevrons, but centered by RenderTransforms instead of Margins) is rendered more consistently, I'm trying to replicate that approach for the ComboBox
> Fix ComboBox button centering 

- samples/SampleApp/DemoPages/MenuDemo.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/Menu.axaml
This completes & corrects the changes from #111 
All of the top-level menu items have visual mouseOver and click feedback.
I also added a `TopLevelMenuItem` class to the `ContentPresenter#PART_HeaderPresenter`, making it easier to apply custom styling (like spacing) to the top-level MenuItems, without affecting the submenus
> [MacOS] Add pointerover behaviours for main MenuItems with Icon & Label side-by-side

- src/Devolutions.AvaloniaTheme.DevExpress/Accents/Icons.axaml
Fixing a bug introduced in #110, where I started pulling icon paths into a separate file, but forgot to add the chevron path
> [DevExpress] Fix missing icon path for CheckBox chevron

- samples/SampleApp/DemoPages/ScrollViewerDemo.axaml
- samples/SampleApp/MainWindow.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/ScrollViewer.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Converters/ThicknessToSelectiveThicknessConverter.cs
- src/Devolutions.AvaloniaTheme.DevExpress/Converters/_index.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml
There seems to be a bug with the ScrollViewer that cuts off the right edge. Apparently it's by design and shouldn't happen when you set `AllowAutoHide=True` - but firstly it still happens then, secondly it shouldn't happen for `AllowAutoHide=False` either, and specifically for the DevExpressTheme it's exacerbated by the fact that 'hiding' the scrollbar doesn't actually increase the viewport size because the track is never hidden.
This fixes the issue for the multiline TextBox. In other scenarios you may need to apply an explicit width to force the right 'padding' you need.
> [DevExpress] Fix ScrollView for multiline TextBox

- samples/SampleApp/SampleApp.csproj
- src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj
- src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj
- src/Devolutions.AvaloniaTheme.MacOS/Devolutions.AvaloniaTheme.MacOS.csproj
This breaks from my usual package bumping routine and sets the Avalonia dependencies within the themes to use minimum version notation (`Version="[11.2.0,)"`) following best practices for nugets - meaning that the theme can pull in whatever version the consuming project is using, rather than forcing up- or downgrades for compatibility. 
One exception is the Fluent theme dependency, since projects using one of our themes typically would not use Fluent as well (and we wouldn't want to inadvertently pull in untested versions). 
Thanks to @Samuel-B-D for prompting me to learn a little bit more about how the version resolution works.
> Update Avalonia packages & make themes compatible with lower version projects

- src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj
- src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj
- src/Devolutions.AvaloniaTheme.MacOS/Devolutions.AvaloniaTheme.MacOS.csproj
Since Avalonia itself is set to minimum 11.2.0 - fixing Fluent to a specific version higher than that creates package downgrade errors (which didn't become apparent straight away with #143, presumably due to various versions still being cached):
```
0>Devolutions.AvaloniaTheme.MacOS.csproj: Error NU1605 : Warning As Error: Detected package downgrade: Avalonia from 11.2.8 to 11.2.0. Reference the package directly from the project to select a different version. 
Devolutions.AvaloniaTheme.MacOS -> Avalonia.Themes.Fluent 11.2.8 -> Avalonia (>= 11.2.8) 
Devolutions.AvaloniaTheme.MacOS -> Avalonia (>= 11.2.0)
0>------- Finished building project: Devolutions.AvaloniaTheme.MacOS. Succeeded: False. Errors: 1. Warnings: 0
2>Devolutions.AvaloniaTheme.Linux.csproj: Error NU1605 : Warning As Error: …
```
> Remove dependency on specific Fluent version

- samples/SampleApp/DemoPages/TextBoxDemo.axaml
- samples/SampleApp/DemoPages/TextBoxDemo.axaml.cs
- samples/SampleApp/ViewModels/TextBoxViewModel.cs
- src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.Linux/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- Fix the DevExpress TextBox error-border which was missing along the bottom. 
- change the dark mode error colour from bright yellow to an off-red that should still offer sufficient contrast
> [All themes] Change dark mode error indicator colour & fix TextBox error border in DevExpress

- src/Devolutions.AvaloniaTheme.DevExpress/Accents/Icons.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBox.axaml
The chevron on the closed combo was modelled on the grayed open state - must have overlooked the difference before.
> [DevExpress] Fix ComboBox chevron (was too thin when closed)

- samples/SampleApp/SampleApp.csproj
Updating the Sample app only, allowing the themes to work with older versions as well. 
Note that the app now generates compiler warnings because Avalonia.Svg.Skia and SkiaSharp still need to be set to require older versions under Linux (see [comment in the code](https://github.com/Devolutions/avalonia-extensions/blob/aa9cbb36f8ac9d739a62bad349afaa76f30f9f56/src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj#L19-L27)
```
2>SampleApp.csproj: Warning NU1608 : Detected package version outside of dependency constraint: Devolutions.AvaloniaTheme.Linux requires Avalonia.Svg.Skia (>= 11.2.0 && < 11.2.7.1) but version Avalonia.Svg.Skia 11.3.0 was resolved.
2>SampleApp.csproj: Warning NU1608 : Detected package version outside of dependency constraint: …
```
> [WIP] Update SampleApp to Avalonia 11.3

- README.md
- samples/SampleApp/App.axaml.cs
- samples/SampleApp/MainWindow.axaml.cs
- samples/SampleApp/SampleApp.csproj
Install new Accelerate Dev Tools and allow users with an appropriate licence to enable them by setting an environment variable: `USE_AVALONIA_ACCELERATE_TOOLS=true` (F12 defaults to new tools then, F10 opens the old ones). 
Everyone else continues to have access to the original free dev tools.
> Use new Accelerate Dev Tools

- samples/SampleApp/DemoPages/ControlAlignment.axaml
- samples/SampleApp/DemoPages/TabControlDemo.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/Button.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/CheckBox.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/ComboBox.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/NumericUpDown.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TabControl.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Converters/ThicknessToSelectiveThicknessConverter.cs
Re-adds a margin around all input controls to accommodate the focus outline. 
This allows us to add controls to a grid (which now supports row-/column-spacing) without any additional properties to be set. (Otherwise the grid itself or potentially other parent containers would always have set `clipToBounds=False` - which is easy to forget, especially for controls that don't show their focus highlight except for keyboard tabbing)
> Mac os/control spacing

- samples/SampleApp/App.axaml.cs
- samples/SampleApp/MainWindow.axaml.cs
When our runtime theme-switching reopens the MainWindow, the code for attaching dev tools is run again - causing Avalonia to throw an exception because the Accelerate dev tools are already attached to the App. Since there seems no way to check, I just added a boolean flag to keep track and prevent multiple calls to `AttachDeveloperTools`
> Prevent DevTools exception during theme switching

- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TabControl.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TabItem.axaml
#154 introduced a slightly more visible little line next to selected tabs, and #155 broke the vertical alignment of the tabstrip to the tab body.
This fixes both, but also removes the previous fragile implementation of the divider lines as pipe characters, replacing them with a border and moving each tab's divider line to the _right_ which allows the next tab's selection border to completely hide the divider (since tabs further to the right are above the previous ones on the z-axis)
Also corrected the body colour for dark mode.
Added a `:selected:pressed` state, but kept the dark mode colour deliberately more subtle than native MacOS, since Avalonia doesn't distinguish between '_already selected & then pressed_' which is supposed to flash a clear "hey, I'm already selected!' colour, and …
> [MacOS] Fix tabs

- src/Devolutions.AvaloniaTheme.DevExpress/Controls/DataGrid.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/DataGrid.axaml
- add border
- add selectable cell
- allow column resize & reorder
- make sure divider lines in the header align with column lines, _if_ someone decides to show them (although by default `GridLinesVisibility="None"` for MacOS)
(& simplify DevExpress FocusVisual)
> [MacOS] Bring DataGrid in line with DevExpress (make style rules inRDM RDM redundant)

- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/DataGrid.axaml
This adds the default background color for DataGrid to the MacOS theme, so all DataGrid related rules can now be deleted from styles.MacOS / moved from styles.axaml to styles.Windows and styles.Linux
> [MacOS] Add default background colour to DataGrid

- samples/SampleApp/DemoPages/DataGridDemo.axaml
- samples/SampleApp/DemoPages/DataGridGroupedDemo.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/DataGrid.axaml
Unfortunately I haven't found a way to make it work equally well for both scenarios: DataGrids that do **not** size the columns to take up all of the space will show an oversized right row margin, unless explicitly marked with `Classes="MacOS_NonDistributed_Columns"`. 
(RDM seems to use `Width="*"` in all cases, so this solution seemed best for our purposes.)
> [MacOS] Fix DataGrid rows when columns are sized to fill the space

- .github/workflows/build-package.yml
[Last week's PR ](https://github.com/Devolutions/avalonia-extensions/pull/168) didn't take into account the scheduled builds on Monday that just test everything still builds properly. The important part about scheduled builds is that "inputs" aren't available, not even the default values, so we have to check for empty values in the preflight step. The build failed because of an empty list of packages to build. I modified the workflow to build an array of packages which is then converted to a string separated by commas, and if the list is empty, it just builds all packages. This also means that if you start a build with everything unchecked, it'll build everything, but I guess that's better than just failing.
> fix nightly build

- samples/SampleApp/App.axaml
- samples/SampleApp/App.axaml.cs
- samples/SampleApp/Controls/SampleItemHeader.axaml
- samples/SampleApp/Controls/SampleItemHeader.axaml.cs
- samples/SampleApp/DemoPages/ButtonDemo.axaml
- samples/SampleApp/DemoPages/DataGridDemo.axaml
- samples/SampleApp/DemoPages/MenuDemo.axaml
- samples/SampleApp/DemoPages/Overview.axaml
- samples/SampleApp/DemoPages/ScrollViewerDemo.axaml
- samples/SampleApp/DemoPages/TextBoxDemo.axaml
- samples/SampleApp/Helpers/ThemeInfo.cs
- samples/SampleApp/MainWindow.axaml
- samples/SampleApp/Styles.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TabControl.axaml
- add a helper that allows us to display different explanations depending on the selected theme 
- clean up some typos and the overview page that was still from the time when we only had the MacOS theme
- indicate on the tabs which controls are actually implemented for the current theme
> Clean up SampleApp

- samples/SampleApp/Controls/SampleItemHeader.axaml
For some reason non-retina displays seem to misjudge the bounds of the status icon when running on Mac ... (perhaps an interesting observation to help with fixing some of the other weird rendering issues on non-retina?)
> [SampleApp] Fix status indicators on non-retina display

- src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBox.axaml
Typing a password (switch from Watermark to actual input) and switching between show/hide password caused small height changes in the TextBox.
> [MacOS / DevExpress] Fix TextBox layout jumps

- src/Devolutions.AvaloniaControls/Converters/HasClassConverter.cs
- src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj
- src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj
- src/Devolutions.AvaloniaTheme.MacOS/Devolutions.AvaloniaTheme.MacOS.csproj
This adds a converter that returns `true` when the given Control's classes do NOT contain a specific class.
(I know the name sounds a bit odd, but I think the pattern of IsX and IsNotX is so well established, that it would seem contrived and less intuitive to give the converter some other name like 'LacksClass' (and it would obscure the simple relationship between this and the existing `HasClass` converter.) 
Unrelated, this also automates the switching between published Devolutions.AvaloniaControls nuget in production and the local assembly during debugging. Thanks to @Samuel-B-D for that idea!
> Add `HasNotClass` converter (& always use local AvaloniaControls in debugging mode)

- samples/SampleApp/DemoPages/ContextMenuDemo.axaml
- samples/SampleApp/DemoPages/ControlAlignment.axaml
- samples/SampleApp/DemoPages/TabControlDemo.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/AutoCompleteBox.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/Button.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBox.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/ComboBoxItem.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/TextBlock.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/_index.axaml
This brings the input controls in MacOS and DevExpress themes to follow the same consistent behaviour when placed together in StackPanels or Grids without any explicit layout properties: no vertical stretching to fill the container height, no default margins, all elements vertically centered.
> Fix alignment & cross-platform consistency issues

- samples/SampleApp/DemoPages/ControlAlignment.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Accents/ThemeResources.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/AutoCompleteBox.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TextBox.axaml
Padding changes in #202 caused the text in TextBox-based inputs to sit slightly lower within the box than the text on other input controls. Just changed the bottom padding to be slightly larger than top padding to fix this & created a shared resource to make sure `AutoComplete` always looks the same as `TextBox`
> Fix TextBox text to align cleanly with other controls' text

- samples/SampleApp/DemoPages/CalendarDatePickerDemo.axaml
- samples/SampleApp/DemoPages/CalendarDatePickerDemo.axaml.cs
- src/Devolutions.AvaloniaTheme.MacOS/Controls/Calendar.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/CalendarDatePicker.axaml
- The last version wasn't flexible enough to accommodate all different date formats. 
- I also didn't realize that it will pick up system settings on date format, so I removed the settings I baked in.
- Plus some code tidying
> [MacOS] Fix DatePicker width for long format & remove format presets

- src/Devolutions.AvaloniaTheme.Linux/Controls/ButtonSpinner.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/CheckBox.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/ContextMenu.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/DataGrid.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/NumericUpDown.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/TabControl.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/TabItem.axaml
- src/Devolutions.AvaloniaTheme.Linux/Controls/TextBox.axaml
- src/Devolutions.AvaloniaTheme.Linux/Design/ThemePreviewer.axaml
- src/Devolutions.AvaloniaTheme.Linux/Design/ThemePreviewer.axaml.cs
- src/Devolutions.AvaloniaTheme.Linux/Devolutions.AvaloniaTheme.Linux.csproj
- src/Devolutions.AvaloniaTheme.Linux/DevolutionsLinuxYaruTheme.cs
This is the design preview wrapper control we're already using for development of the DevExpress and MacOS themes for easy light & dark mode preview. Just copying it to the Linux project.
> Add Design ThemePreviewer to the Linux project

- samples/SampleApp/DemoPages/ListBoxDemo.axaml
- samples/SampleApp/DemoPages/ListBoxDemo.axaml.cs
- samples/SampleApp/DemoPages/TabControlDemo.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/TabControl.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Devolutions.AvaloniaTheme.DevExpress.csproj
Changes `TabControl`'s `VerticalContentAlignment` from `Top` to `Stretch` to avoid confusing behaviour of child components. 
(All other changes are just in the demo pages to better illustrate/test alignment issues like the one that prompted this change)
> [DevExpress] Change TabControl VerticalContentAlignment

- samples/SampleApp/App.axaml
- samples/SampleApp/DemoPages/MultiComboBoxDemo.axaml
- samples/SampleApp/ViewModels/MultiComboBoxViewModel.cs
- src/Devolutions.AvaloniaControls/Controls/MultiComboBox/MultiComboBox.axaml
- src/Devolutions.AvaloniaControls/Controls/MultiComboBox/MultiComboBox.axaml.cs
- src/Devolutions.AvaloniaControls/Controls/MultiComboBox/MultiComboBoxItem.axaml
- src/Devolutions.AvaloniaTheme.DevExpress/Controls/MultiComboBoxItem.axaml
- src/Devolutions.AvaloniaTheme.MacOS/Controls/MultiComboBoxItem.axaml
`ItemTemplate` is a regular functionnality of `ItemsControl`, but I didn't support it correctly in the original implementation of `MultiComboBox` due to forgetting to bind the `ContentTemplate` properly on the `ContentPresenter` of the items.
I also added a little bit of logic to use the `ItemTemplate` in the SelectedItem's template when a specific `SelectedItemTemplate` is not provided, so that by default, if you specify an `ItemTemplate`, the `ClosableTag`s will display the same template as the items unless overriden.
> Support ItemTemplate in MultiComboBox

- src/Devolutions.AvaloniaTheme.MacOS/Controls/CheckBox.axaml
Just realized that the styling of a checked and disabled CheckBox broke way back when I added colour changes on Window-inactive ... 
Also, I never implemented the subtle mouseDown feedback on CheckBoxes. 
This fixes both.
> [MacOS] Fix CheckBox :disabled:checked states & add :pressed state styling
